baseURL = "https://nicoloval.github.io/mbch/"
languageCode = "en-us"
title = "Midnight Book Club "
theme = "midnnight"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[Params]
  email = "nico.vallarano at gmail.com"

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Links"
  url = "/links"

[[menu.main]]
  name = "Instagram"
  url = "https://nicoloval.github.io/mbch/"

[[menu.main]]
  name = "Tags"
  url = "tags/"
