baseURL = "https://nicoloval.github.io/mbch/"
languageCode = "en-us"
title = "Midnight Book Club "
theme = "midnnight"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[Params]
  email = "nico.vallarano at gmail.com"

[[menu.main]]
  name = "Links"
  url = "links"

[[menu.main]]
  name = "Instagram"
  url = "https://www.instagram.com/l_incredibile_hulk/"

[[menu.main]]
  name = "Tags"
  url = "tags/"
