baseURL = "https://nicoloval.github.io/mbch/"
languageCode = "en-us"
title = "Midnight"
theme = "midnnight"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[Params]
  email = "midnight@fake.mail"

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Instagram"
  url = "https://www.instagram.com/"

[[menu.main]]
  name = "Tags"
  url = "tags/"
