baseURL = "https://nicoloval.github.io/mbch/"
languageCode = "en-us"
title = "Midnight"
theme = "midnnight"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[Params]
  instagram = "https://www.instagram.com/"
